CREATE TABLE IF NOT EXISTS RESTAURANTS(
  ID UUID PRIMARY KEY,
  NAME VARCHAR(255),
  PHOTO VARCHAR(255),
  ADDRESS VARCHAR(255),
  NUMBER VARCHAR(255),
  NEIGHBORHOOD VARCHAR(255),
  CITY VARCHAR(255),
  STATE CHAR(2),
  COUNTRY VARCHAR(255),
  POSTAL_CODE VARCHAR(255)
);
