CREATE TABLE IF NOT EXISTS PROMOTIONS(
  ID UUID PRIMARY KEY,
  DESCRIPTION VARCHAR(255),
  PRICE_PROMOTION DECIMAL(6,2),
  START_DATE DATE,
  FINISH_DATE DATE,
  START_TIME TIME,
  FINISH_TIME TIME,
  PRODUCT_ID UUID
);
