CREATE TABLE IF NOT EXISTS RESTAURANTS(
  ID UUID PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PHOTO VARCHAR(255),
  ADDRESS VARCHAR(255),
  NUMBER VARCHAR(255),
  NEIGHBORHOOD VARCHAR(255),
  CITY VARCHAR(255),
  STATE CHAR(2),
  COUNTRY VARCHAR(255),
  POSTAL_CODE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS OPENING_HOURS(
  ID UUID PRIMARY KEY NOT NULL,
  WEEKDAY VARCHAR(255),
  START_TIME TIME,
  FINISH_TIME TIME,
  RESTAURANT_ID UUID,
  CONSTRAINT FK_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
  ID UUID PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  RESTAURANT_ID UUID,
  CONSTRAINT FK_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
  ID UUID PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PHOTO VARCHAR(255),
  PRICE DECIMAL(6,2),
  CATEGORY_ID UUID,
  RESTAURANT_ID UUID,
  CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID) ON DELETE SET NULL,
  CONSTRAINT FK_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PROMOTIONS(
  ID UUID PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRICE_PROMOTION DECIMAL(6,2),
  START_DATE DATE,
  FINISH_DATE DATE,
  START_TIME TIME,
  FINISH_TIME TIME,
  PRODUCT_ID UUID,
  CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID) ON DELETE CASCADE
);
