version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=goomer_lista_rango
    volumes:
      - ./src/database/migrations/createTables.sql:/docker-entrypoint-initdb.d/createRestaurant.sql

  app:
    build: .
    container_name: goomer-lista-rango
    command:
      sh -c "yarn build && yarn start"
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    environment:
      - HOST=database
    depends_on:
      - database

